### ISSUE TITLE
Adding multithreaded based scanning

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Photoroid#2]
**Objective** :  Matching multiple images at the same time using multi-threading.

**Comment by VishalS99** [comment]
Hey, I would like to take this up!

**Comment by 0xPrateek** [comment]
Can you please write your approach for working out on this issue?

**Comment by VishalS99** [comment]
Yeah, so, at present what I have done is created threads that will be used to dissect the template into multiple sub images, and then created a thread for every image to be checked against. I have gotten a speed up of approx 2.5

**Comment by VishalS99** [comment]
With the current images part of the repo itself, the original code ran for 0. 46 ms whereas the threaded version ran for 0.2 ms

**Comment by VishalS99** [comment]
Is this method good enough?

**Comment by VishalS99** [comment]
Shall I give a PR?

**Comment by 0xPrateek** [comment]
I was thinking we should first fix the issue we all working on #11 and #8  because it would be easy for us.

**Comment by VishalS99** [comment]
Hmm okay

**Comment by VishalS99** [comment]
But anyways I'll push the code, so that you can check and see if the my current method for multithreading is okay?

**Comment by VishalS99** [comment]
Also I've analysed and understood that multithreading is not actual multithreading in python. Instead iam gonna try multi processing

**Comment by VishalS99** [comment]
We can also update the current threaded version for the new algorithm. I have properly separated the code so that any new algo can easily be added to it

**Comment by 0xPrateek** [comment]
Sounds Good..! Anything that improves photoroid is accepted. I'll take a look at your PR.
