### ISSUE TITLE
Adding windows color support

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Photoroid#3]

**Comment by VishalS99** [comment]
I would like to take up this problem. Could please elaborate a bit more?

**Comment by 0xPrateek** [comment]
currently, we are printing colored lines using `ANSI escape sequences` which is supported in Linux and Mac but not supported by windows.
You should either find an alternative for printing colored lines that support windows as well or find a solution to fix using `ANSI escape sequences` only.

**Comment by VishalS99** [comment]
Okay I'll look into it the forth coming days

**Comment by VishalS99** [comment]
At present, there is a python package called colorama, the does the same and is very well supported.
