### ISSUE TITLE
Writing docs for photoroid

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Photoroid#4]

**Comment by VishalS99** [comment]
I would like to take up this problem.

**Comment by 0xPrateek** [comment]
Great..! I am assigning you for this issue. Make sure you comment down the updates as you progress.(It will tell us that you are working on it or not.)

**Comment by VishalS99** [comment]
Do you want it as Wiki pages or readme files?

**Comment by 0xPrateek** [comment]
I was thinking of Wiki pages.
What do you say which will be good?

**Comment by RedDocMD** [comment]
I think a markdown file will be good since it can easily be converted into a webpage and a pdf. However, if Wiki pages have a specific format, then this idea will not work.

**Comment by 0xPrateek** [comment]
@VishalS99  Go with creating readme file. It would be more convenient.
I am assigning you this issue and you make sure that you update your progress through commenting on this issue so that we can confirm that you are working on it.

**Comment by VishalS99** [comment]
Okay cool, I'll start working on it.
