### ISSUE TITLE
Adding comments in code for increasing code readbility

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Photoroid#5]

**Comment by nithinBharadwaj369** [comment]
Hi prateek, it only makes sense if the person who wrote the code writes the comments. People may misinterpret in general. So use docstrings in each function. I think you can use classes. Just a suggestion.

**Comment by 0xPrateek** [comment]
I agree with you. But, the reason I have created this issue because I want some beginner friendly issues so that beginners can contribute to open source. Yes, we can use classes but I mostly prefer to use classes when there is some good number of functions written in the program.
