### ISSUE TITLE
Use PEP-8 code formatting 

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Photoroid#7]
Use PEP-8 standard for formatting code.
you can read about it [here](https://www.python.org/dev/peps/pep-0008/).
- For this, run the whole code through a pep-8 formatter and update new codes here.

**Comment by RedDocMD** [comment]
I have formatted the files according to PEP-8 standard and would like to submit the code

**Comment by VishalS99** [comment]
I have completed the formatting, and have given a PR
Could please check it out?

**Comment by 0xPrateek** [comment]
@VishalS99 I could not accept your PR since @RedDocMD He was working on this issue and he has already formatted the code in pep-8 style in his forked code. If you have gone through the official communication channel then I have told him there to wait for 7th Dec so that the pull request he make gets counted in kwoc.
Hope you understand.

**Comment by VishalS99** [comment]
@0xPrateek Oh sorry, my bad!

**Comment by 0xPrateek** [comment]
No Worries..! @VishalS99  Still there are a lot of issues, improvements to be fixed and not just this you can come up with your own features, add-ons.
