### ISSUE TITLE
Improving command-line arguments and changing hard-coded paths for image files

### ISSUE THREAD

**Issue by RedDocMD** [0xPrateek/Photoroid#9]
Currently, Photoroid does not run as a **script**. It also has the template image storage directory as well as the images-to-match directory **hard-coded**. These can be entered by the user **interactively** as well as directly from the command-line via arguments.

**Comment by RedDocMD** [comment]
I would like to work on resolving this issue

**Comment by 0xPrateek** [comment]
Sounds Good..! I am assigning you for this issue. Make sure to update your progress by commenting on this issue.

**Comment by RedDocMD** [comment]
I am going to make a wrapper script in Bash. This will work in Linux and Mac, and Windows as well since Windows now natively supports Bash scripts.
